comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  branches:
    - "master"

coverage:
  status:
    project:
      default:
        threshold: 90%
    patch: true